---
- name: create users and copy files into the users home dirs
  hosts: all
  tasks:
    - name: create multiple users
      user:
        name: "{{item.a}}"
        password: "{{item.b}}"
        home: "{{item.c}}"
      with_items:
        - {a:satish,b: intelliqit,c: /home/satish}
        - {a:ramesh,b: intelliqit,c: /tmp/ramesh}
    - name: copy files into users home dir
      copy:
        src: "{{item.a}}"
        dest: "{{item.b}}"
      with_items:
        - {a: /etc/passwd,b: /home/satish}
        - {a: /etc/group,b: /tmp/ramesh}
...
